# Generated by Django 4.2.1 on 2023-05-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='direccion',
            field=models.CharField(default='por ahi 123', max_length=150),
        ),
    ]
